  pipeline:
    - svd1

  config:
    svd1:
      command: 'svd_tool'
      input_proto: '../VGG16ORI_new.prototxt'
      input_caffemodel: '../VGG16ORI_new.caffemodel'
      output_proto: './output_vgg16_svd_fc6_rank512.prototxt'
      output_caffemodel: './output_vgg16_svd_fc6_rank512.caffemodel'
      pre-validate: True
      layers:
        - 'fc6, rank, 512'
