  pipeline:
    #- conv1
    - svd1

  config:
    svd1:
      command: 'svd_tool'
      input_proto: '../VGG16ORI_new.prototxt'
      input_caffemodel: '../VGG16ORI_new.caffemodel'
      output_proto: './try4.prototxt'
      output_caffemodel: './try4.caffemodel'
      pre-validate: True
      layers:
        - 'fc6, rank, 512'
